<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.77" />
		<PackageReference Include="MahApps.Metro" Version="2.4.10" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Views\AddPresetWindow.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Views\CreateVersionWindow.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Views\ServerSettingsWindow.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Views\VersionConflictWindow.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
		<Compile Update="Views\VersionsWindow.xaml.cs">
			<SubType>Code</SubType>
		</Compile>
	</ItemGroup>
</Project>
