<Project Sdk="Microsoft.NET.Sdk.Worker">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dotnet-TrayApplicationWithWorkerServiceTest-22cd42a8-82f2-461a-9b6b-2eef88bf773d</UserSecretsId>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
	</ItemGroup>
</Project>
